spring:
  application:
    name: chatbot
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT}/chatbot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#     show-sql: true
openai:
  api-key: ${OPENAI_API_SECRET_KEY}
  api-url: https://api.openai.com/v1/chat/completions # GPT 대화용 API URL
  model: gpt-3.5-turbo


#    show-sql: true

